// src/components/menu-item.component.tsx
import { useContext } from "solid-js"
import { MenuItem as MenuItemModel } from "../services/model"
import { MenuContext } from "../store/menu.store"
import { OrderContext } from "../store/order.store"
import "./menu-item.style.css"

interface Props {
  menuItem: MenuItemModel
}

function MenuItem({ menuItem }: Props) {
  const [menuState, { remove }] = useContext(MenuContext)
  const [_, { add }] = useContext(OrderContext)

  const addOrderItem = () => add(menuItem)
  const removeMenuItem = () => remove(menuItem)

  return (
    <div class="menu-item-wrapper">
      <span>{menuItem}</span>
      <button onClick={addOrderItem}>Add</button>
      <button onClick={removeMenuItem}>Delete</button>
    </div>
  )
}

export default MenuItem

// src/components/MenuItem.vue
<template>
  <ListItem @remove="remove">
    <button @click="addToCommand">{{menuItem}}</button>
  </ListItem>
</template>

<script setup lang="ts">
import { MenuItem } from '../services/model';
import { useMenuStore } from '../stores/menu.store';
import { useCommandStore } from '../stores/command.store';
import ListItem from './ListItem.vue'


interface Props {
  menuItem : MenuItem
}

const props = defineProps<Props>()
const menuStore = useMenuStore()
const commandStore = useCommandStore()

const remove = () => {
  menuStore.remove(props.menuItem)
}

const addToCommand = () => {
  commandStore.add(props.menuItem)
}


</script>
