// src/components/Menu.tsx
import { useContext } from "react";
import { AppContext } from "../context/AppContext";
import MenuItem from "./MenuItem";
import NewMenuItem from "./NewMenuItem";

const Menu: React.FC = () => {
  const { removeFromMenu, addToOrder, menuItems } = useContext(AppContext);

  return (
    <section className="menu">
      <h2>Menu</h2>
      <NewMenuItem />
      {menuItems.map((item) => (
        <MenuItem
          key={item}
          item={item}
          addToOrder={addToOrder}
          removeFromMenu={removeFromMenu}
        />
      ))}
    </section>
  );
};

export default Menu;

// src/components/Menu.vue
<template>
  <div>
    <NewMenuItem></NewMenuItem>
    <MenuItem
      v-for="menuItem in menu"
      :key="menuItem"
      :menu-item="menuItem"
    ></MenuItem>
  </div>
</template>

<script setup lang="ts">
import { Menu } from "../services/model"
import NewMenuItem from "./NewMenuItem.vue"
import MenuItem from "./MenuItem.vue"

interface Props {
  menu: Menu
}

defineProps<Props>()
</script>
