// src/components/new-menu-item.component.tsx
import { createSignal, useContext } from "solid-js"
import { MenuContext } from "../store/menu.store"
import "./new-menu-item.style.css"

function NewMenuItem() {
  const [newName, setNewName] = createSignal<string>("")

  const [state, { add }] = useContext(MenuContext)

  const formSubmit = async (event: Event) => {
    event.preventDefault()
    add(newName())
    setNewName("")
  }

  return (
    <form onSubmit={formSubmit}>
      <input
        type="text"
        name="new-item"
        onInput={(e) => setNewName((e.target as HTMLInputElement).value)}
        value={newName()}
      />
      <button type="submit">Add</button>
    </form>
  )
}

export default NewMenuItem

// src/components/NewMenuItem.tsx
import { FormEvent, useContext, useState } from "react";
import { AppContext } from "../context/AppContext";

const NewMenuItem: React.FC = () => {
  const { loading, addToMenu } = useContext(AppContext);
  const [newMenuItem, setNewMenuItem] = useState("");

  const submitNewMenuItem = (e: FormEvent) => {
    e.preventDefault();
    addToMenu(newMenuItem);
  };

  const onChangeNewMenuItem = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewMenuItem(e.target.value);
  };

  return (
    <form onSubmit={submitNewMenuItem}>
      <input
        type="text"
        id="new-menu-input"
        disabled={loading}
        placeholder="New menu item"
        required
        value={newMenuItem}
        onChange={onChangeNewMenuItem}
      />
      <button type="submit">Add</button>
    </form>
  );
};

export default NewMenuItem;
