// src/components/NewMenuItem.tsx
import { FormEvent, useContext, useState } from "react";
import { AppContext } from "../context/AppContext";

const NewMenuItem: React.FC = () => {
  const { loading, addToMenu } = useContext(AppContext);
  const [newMenuItem, setNewMenuItem] = useState("");

  const submitNewMenuItem = (e: FormEvent) => {
    e.preventDefault();
    addToMenu(newMenuItem);
  };

  const onChangeNewMenuItem = (e: React.ChangeEvent<HTMLInputElement>) => {
    setNewMenuItem(e.target.value);
  };

  return (
    <form onSubmit={submitNewMenuItem}>
      <input
        type="text"
        id="new-menu-input"
        disabled={loading}
        placeholder="New menu item"
        required
        value={newMenuItem}
        onChange={onChangeNewMenuItem}
      />
      <button type="submit">Add</button>
    </form>
  );
};

export default NewMenuItem;

// src/components/NewMenuItem.vue
<template>
  <form @submit.prevent="add">
    <input
      type="text"
      name="new-item"
      required
      placeholder="New Menu item"
      v-model="newItemName"
    />
    <button type="submit">Add</button>
  </form>
</template>

<script setup lang="ts">
import { ref } from "vue"
import { useMenuStore } from "../stores/menu.store"

const menuStore = useMenuStore()

const newItemName = ref("")

const add = () => {
  if (!newItemName.value) {
    return
  }

  menuStore.add(newItemName.value)
  newItemName.value = ''
}
</script>
